return {{[ [[last_hp]] ] = 2283,[ [[fsPrivateChat]] ] = 8,[ [[fsMapCompass]] ] = 7,[ [[page]] ] = [[a]],[ [[widgets]] ] = {2},[ [[fsKeybind]] ] = 6,[ [[last_mana]] ] = 864,[ [[enablePugno]] ] = true,[ [[last_hp_opponent]] ] = 0,[ [[fsPublicChat]] ] = 8,[ [[fsHelp]] ] = 8,[ [[fsEquipment]] ] = 8,[ [[fsInventory]] ] = 8,},
{[ [[endowment]] ] = {3},[ [[overland]] ] = {4},[ [[keybind]] ] = {5},[ [[group]] ] = {6},[ [[aliasButton]] ] = {7},[ [[chat]] ] = {8},[ [[mapper]] ] = {9},[ [[player]] ] = {10},[ [[help]] ] = {11},[ [[affects]] ] = {12},[ [[cooldowns]] ] = {13},[ [[targets]] ] = {14},[ [[room]] ] = {15},[ [[opponent]] ] = {16},},
{[ [[type]] ] = [[equip]],[ [[transparent]] ] = false,},
{[ [[fontSize]] ] = 8,},
{[ [[fontSize]] ] = 6,},
{[ [[transparent]] ] = false,},
{[ [[transparent]] ] = false,},
{[ [[type]] ] = [[all]],[ [[fontSize]] ] = 10,[ [[split]] ] = [[horizontal]],},
{[ [[transparent]] ] = false,},
{[ [[transparent]] ] = false,},
{[ [[fontSize]] ] = 10,},
{[ [[transparent]] ] = false,},
{[ [[transparent]] ] = false,},
{[ [[transparent]] ] = false,},
{[ [[fontSize]] ] = 10,[ [[transparent]] ] = false,},
{[ [[transparent]] ] = false,},
}