return {{[ [[enablePugno]] ] = true,[ [[page]] ] = [[a]],[ [[widgets]] ] = {2},},
{[ [[inventory]] ] = {3},[ [[overland]] ] = {4},[ [[publicChat]] ] = {5},[ [[keybind]] ] = {6},[ [[group]] ] = {7},[ [[privateChat]] ] = {8},[ [[aliasButton]] ] = {9},[ [[chat]] ] = {10},[ [[equipment]] ] = {11},[ [[player]] ] = {12},[ [[help]] ] = {13},[ [[affects]] ] = {14},[ [[affect]] ] = {15},[ [[room]] ] = {16},[ [[mapper]] ] = {17},[ [[opponent]] ] = {18},},
{[ [[fontSize]] ] = 8,},
{[ [[fontSize]] ] = 8,},
{[ [[fontSize]] ] = 8,},
{[ [[fontSize]] ] = 6,},
{[ [[transparent]] ] = true,},
{[ [[fontSize]] ] = 8,},
{[ [[transparent]] ] = true,},
{[ [[type]] ] = [[all]],[ [[fontSize]] ] = 10,[ [[split]] ] = true,},
{[ [[fontSize]] ] = 8,},
{[ [[transparent]] ] = false,},
{[ [[fontSize]] ] = 12,},
{[ [[trasparent]] ] = false,[ [[transparent]] ] = true,},
{[ [[trasparent]] ] = false,},
{[ [[fontSize]] ] = 7,[ [[transparent]] ] = true,},
{[ [[transparent]] ] = false,},
{[ [[transparent]] ] = false,},
}