return {{[ [[enablePugno]] ] = true,[ [[page]] ] = [[a]],[ [[widgets]] ] = {2},},
{[ [[inventory]] ] = {3},[ [[overland]] ] = {4},[ [[mapper]] ] = {5},[ [[group]] ] = {6},[ [[targets]] ] = {7},[ [[chat]] ] = {8},[ [[help]] ] = {9},[ [[affects]] ] = {10},[ [[affect]] ] = {11},[ [[endowment]] ] = {12},[ [[keybind]] ] = {13},[ [[aliasButton]] ] = {14},[ [[equipment]] ] = {15},[ [[room]] ] = {16},[ [[privateChat]] ] = {17},[ [[publicChat]] ] = {18},[ [[player]] ] = {19},[ [[opponent]] ] = {20},},
{[ [[fontSize]] ] = 8,},
{[ [[fontSize]] ] = 8,},
{[ [[transparent]] ] = false,},
{[ [[transparent]] ] = true,},
{[ [[transparent]] ] = false,},
{[ [[type]] ] = [[private]],[ [[fontSize]] ] = 10,[ [[split]] ] = [[horizontal]],},
{[ [[fontSize]] ] = 12,},
{[ [[trasparent]] ] = false,[ [[transparent]] ] = true,},
{[ [[trasparent]] ] = false,},
{[ [[type]] ] = [[inv]],[ [[fontSize]] ] = 8,},
{[ [[fontSize]] ] = 6,},
{[ [[transparent]] ] = true,},
{[ [[fontSize]] ] = 8,},
{[ [[fontSize]] ] = 8,[ [[transparent]] ] = true,},
{[ [[fontSize]] ] = 8,},
{[ [[fontSize]] ] = 8,},
{[ [[transparent]] ] = false,},
{[ [[transparent]] ] = false,},
}