return {{[ [[str]] ] = {2},[ [[ggg]] ] = {3},[ [[buff]] ] = {4},[ [[shield]] ] = {5},[ [[cr]] ] = {6},[ [[g]] ] = {7},[ [[astral]] ] = {8},[ [[ca]] ] = {9},[ [[le]] ] = {10},[ [[pavese]] ] = {11},[ [[aura]] ] = {12},[ [[chiaro]] ] = {13},[ [[cell]] ] = {14},[ [[morsa]] ] = {15},[ [[ga]] ] = {16},[ [[www]] ] = {17},[ [[p]] ] = {18},[ [[ppp]] ] = {19},[ [[dw]] ] = {20},[ [[great]] ] = {21},[ [[gg]] ] = {22},[ [[over]] ] = {23},[ [[ipno]] ] = {24},[ [[xxx]] ] = {25},[ [[cham]] ] = {26},[ [[dis]] ] = {27},[ [[im]] ] = {28},[ [[tele]] ] = {29},[ [[es]] ] = {30},[ [[bash]] ] = {31},[ [[attack]] ] = {32},[ [[dro]] ] = {33},[ [[mano]] ] = {34},[ [[sanc]] ] = {35},[ [[bl]] ] = {36},[ [[scry]] ] = {37},[ [[sense]] ] = {38},[ [[psi]] ] = {39},[ [[myopen]] ] = {40},[ [[autoattack]] ] = {41},[ [[op]] ] = {42},[ [[lp]] ] = {43},[ [[tt]] ] = {44},[ [[rp]] ] = {45},[ [[rr]] ] = {46},[ [[pp]] ] = {47},[ [[minibuff]] ] = {48},[ [[ep]] ] = {49},[ [[flame]] ] = {50},[ [[portal]] ] = {51},[ [[pugno]] ] = {52},[ [[extra]] ] = {53},[ [[blank]] ] = {54},[ [[xx]] ] = {55},[ [[vel]] ] = {56},[ [[sfera]] ] = {57},[ [[cani]] ] = {58},[ [[sum]] ] = {59},[ [[x]] ] = {60},[ [[fly]] ] = {61},[ [[ub]] ] = {62},[ [[bu]] ] = {63},[ [[ap]] ] = {64},},
{[ [[text]] ] = [[mind 'forza psichica']],},
{[ [[text]] ] = [[g @bag2/get # @bag2/p @bag2]],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F10]],[ [[text]] ] = [[minibuff / shield / rp / lp]],[ [[mod1]] ] = [[]],},
{[ [[text]] ] = [[mind 'scudo psichico']],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F3]],[ [[text]] ] = [[mind 'frantumazione psichica' @target]],[ [[mod1]] ] = [[]],},
{[ [[text]] ] = [[get # @bag]],},
{[ [[text]] ] = [[mind 'viaggio probabilistico']],},
{[ [[text]] ] = [[close north/close east/close south/close west/close up/close down]],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F4]],[ [[text]] ] = [[mind 'lampo di energia' @target]],[ [[mod1]] ] = [[]],},
{[ [[text]] ] = [[rem sfera/pp sfera/gg pavese/wear pavese]],},
{[ [[text]] ] = [[mind 'aura veggente']],},
{[ [[text]] ] = [[mind 'chiaroveggenza']],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F12]],[ [[text]] ] = [[mind 'riparazione cellulare']],[ [[mod1]] ] = [[]],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F7]],[ [[text]] ] = [[mind 'morsa brutale' @target]],[ [[mod1]] ] = [[]],},
{[ [[text]] ] = [[get all]],},
{[ [[text]] ] = [[where spirito/where massa/where forma/where corpo/where mostro]],},
{[ [[text]] ] = [[put # @bag]],},
{[ [[text]] ] = [[g @bag2/put # @bag2/p @bag2]],},
{[ [[text]] ] = [[mind 'trasferimento']],},
{[ [[text]] ] = [[mind 'grande vista']],},
{[ [[text]] ] = [[g @bag1/get # @bag1/p @bag1]],},
{[ [[text]] ] = [[mind 'mente oltre il corpo']],},
{[ [[text]] ] = [[mind 'ipnosi']],},
{[ [[text]] ] = [[g @bag2/x @bag2/p @bag2]],},
{[ [[text]] ] = [[mind 'camaleonte']],},
{[ [[text]] ] = [[mind 'lampo di energia' @target]],},
{[ [[text]] ] = [[info mob]],},
{[ [[text]] ] = [[mind 'teletrasporto psichico']],},
{[ [[text]] ] = [[enter specchio]],},
{[ [[text]] ] = [[mind 'schiaffo violento' @target]],},
{[ [[text]] ] = [[bl]],},
{[ [[text]] ] = [[mind 'scarica di adrenalina']],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F9]],[ [[text]] ] = [[mind 'mano di energia' @target]],[ [[mod1]] ] = [[]],},
{[ [[text]] ] = [[gg raven/tt raven/usa scettro/rr raven/pp raven]],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F1]],[ [[text]] ] = [[mind 'colpo psichico' @target]],[ [[mod1]] ] = [[]],},
{[ [[text]] ] = [[mind 'visione']],},
{[ [[text]] ] = [[mind 'senso del pericolo']],},
{[ [[text]] ] = [[mind 'invisibilita psichica']],},
{[ [[text]] ] = [[open #/push #/pull #/turn #/lift #/twist #]],},
{[ [[text]] ] = [[aa]],},
{[ [[text]] ] = [[pick # / unlock # / open # / doorb #]],},
{[ [[text]] ] = [[mind 'lame psioniche']],},
{[ [[text]] ] = [[rem @weapon/tieni #]],},
{[ [[text]] ] = [[mind 'rinforzo psichico' @stat]],},
{[ [[text]] ] = [[rem #/wi @weapon]],},
{[ [[text]] ] = [[g @bag1/put # @bag1/p @bag1]],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F11]],[ [[text]] ] = [[flame / dro Kyrus]],[ [[mod1]] ] = [[]],},
{[ [[text]] ] = [[enter portal]],},
{[ [[text]] ] = [[mind 'mantello di fiamme']],},
{[ [[text]] ] = [[mind 'portale psichico']],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F8]],[ [[text]] ] = [[mind 'pugno serrato' @target]],[ [[mod1]] ] = [[]],},
{[ [[text]] ] = [[mind 'percezione extrasensoriale']],},
{[ [[text]] ] = [[mind 'vuoto mentale']],},
{[ [[text]] ] = [[g @bag1/x @bag1/p @bag1]],},
{[ [[text]] ] = [[enve lee]],},
{[ [[text]] ] = [[rem pavese/pp pavese/gg rutilante/wear rutilante]],},
{[ [[text]] ] = [[mind 'cannibalizzare']],},
{[ [[text]] ] = [[mind 'evocazione psichica']],},
{[ [[text]] ] = [[examine]],},
{[ [[text]] ] = [[mind 'levitazione']],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F6]],[ [[text]] ] = [[mind 'colpo superiore']],[ [[mod1]] ] = [[]],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F5]],[ [[text]] ] = [[mind 'manipola fiamme' espandi]],[ [[mod1]] ] = [[]],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F2]],[ [[text]] ] = [[mind 'assalto psionico' @target]],[ [[mod1]] ] = [[]],},
}