return {{[ [[es]] ] = {2},[ [[ident]] ] = {3},[ [[lampo]] ] = {4},[ [[co]] ] = {5},[ [[disarm]] ] = {6},[ [[g]] ] = {7},[ [[cel]] ] = {8},[ [[chiaro]] ] = {9},[ [[morsa]] ] = {10},[ [[rin]] ] = {11},[ [[golame]] ] = {12},[ [[pi]] ] = {13},[ [[ppp]] ] = {14},[ [[astral]] ] = {15},[ [[mfc]] ] = {16},[ [[gg]] ] = {17},[ [[over]] ] = {18},[ [[dro]] ] = {19},[ [[ii]] ] = {20},[ [[x]] ] = {21},[ [[xxx]] ] = {22},[ [[tt]] ] = {23},[ [[as]] ] = {24},[ [[ga]] ] = {25},[ [[bash]] ] = {26},[ [[minibuff]] ] = {27},[ [[mfe]] ] = {28},[ [[mano]] ] = {29},[ [[cani]] ] = {30},[ [[bl]] ] = {31},[ [[scry]] ] = {32},[ [[ramo]] ] = {33},[ [[sanc]] ] = {34},[ [[scudo]] ] = {35},[ [[pugno]] ] = {36},[ [[op]] ] = {37},[ [[buff]] ] = {38},[ [[ggg]] ] = {39},[ [[goalma]] ] = {40},[ [[gogreylin]] ] = {41},[ [[rr]] ] = {42},[ [[autoattack]] ] = {43},[ [[ext]] ] = {44},[ [[flame]] ] = {45},[ [[blink]] ] = {46},[ [[pp]] ] = {47},[ [[psi]] ] = {48},[ [[sense]] ] = {49},[ [[p]] ] = {50},[ [[shield]] ] = {51},[ [[xx]] ] = {52},[ [[vuoto]] ] = {53},[ [[depoall]] ] = {54},[ [[lame]] ] = {55},[ [[cham]] ] = {56},[ [[ub]] ] = {57},[ [[mfp]] ] = {58},[ [[cr]] ] = {59},},
{[ [[text]] ] = [[enter specchio]],},
{[ [[text]] ] = [[ispeziona # ident]],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F4]],[ [[text]] ] = [[mind 'lampo di energia' &target]],[ [[mod1]] ] = [[]],},
{[ [[text]] ] = [[close #/open #]],},
{[ [[text]] ] = [[gg scasso/tt scasso/usa scasso #/rr scasso/pp scasso]],},
{[ [[text]] ] = [[get # &bag]],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F12]],[ [[text]] ] = [[mind 'riparazione cellulare']],[ [[mod1]] ] = [[]],},
{[ [[text]] ] = [[mind 'chiaroveggenza']],},
{[ [[text]] ] = [[mind 'morsa brutale' &target]],},
{[ [[text]] ] = [[mind 'rinforzo psichico' &stat]],},
{[ [[text]] ] = [[uigo 20033]],},
{[ [[text]] ] = [[mind 'pensiero imponente' &target]],},
{[ [[text]] ] = [[g &bag3/put # &bag3/p &bag3]],},
{[ [[text]] ] = [[mind 'viaggio probabilistico']],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F7]],[ [[button]] ] = [[a3]],[ [[text]] ] = [[mind 'manipola fiamme' convoglia]],[ [[mod1]] ] = [[]],},
{[ [[text]] ] = [[g &bag2 / get # &bag2 / p &bag2]],},
{[ [[text]] ] = [[mind 'mente oltre il corpo']],},
{[ [[text]] ] = [[mind 'scarica di adrenalina']],},
{[ [[text]] ] = [[investiga]],},
{[ [[text]] ] = [[exam &bag]],},
{[ [[text]] ] = [[g &bag3/exam &bag3/p &bag3]],},
{[ [[text]] ] = [[rem &hold/tieni #]],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F3]],[ [[button]] ] = [[a2]],[ [[text]] ] = [[mind 'assalto psionico' &target]],[ [[mod1]] ] = [[]],},
{[ [[text]] ] = [[get all]],},
{[ [[text]] ] = [[mind 'schiaffo violento' &target]],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F11]],[ [[text]] ] = [[flame/rin/shield/psi]],[ [[mod1]] ] = [[]],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F5]],[ [[text]] ] = [[mind 'manipola fiamme' espandi]],[ [[mod1]] ] = [[]],},
{[ [[text]] ] = [[mind 'mano di energia']],},
{[ [[text]] ] = [[mind 'cannibalizzare']],},
{[ [[button]] ] = [[a0]],[ [[text]] ] = [[mind 'colpo psichico' &target]],},
{[ [[text]] ] = [[mind 'visione']],},
{[ [[text]] ] = [[rem scudo / p scudo / g ramo / hold ramo]],},
{[ [[text]] ] = [[gg pergamena-luminescente / tt pergamena-luminescente / reci pergamena / tieni &hold]],},
{[ [[text]] ] = [[rem ramo / p ramo / g scudo / wear scudo]],},
{[ [[text]] ] = [[mind 'pugno serrato' &target]],},
{[ [[text]] ] = [[unlock #/open #]],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F10]],[ [[text]] ] = [[lame/minibuff]],[ [[mod1]] ] = [[]],},
{[ [[text]] ] = [[g &bag3/get # &bag3/p &bag3]],},
{[ [[text]] ] = [[uigo 3001]],},
{[ [[text]] ] = [[uigo 6246]],},
{[ [[text]] ] = [[rem # / wi &weapon / tieni &hold]],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F1]],[ [[text]] ] = [[aa]],[ [[mod1]] ] = [[]],},
{[ [[text]] ] = [[mind 'percezione extrasensoriale']],},
{[ [[text]] ] = [[mind 'mantello di fiamme']],},
{[ [[text]] ] = [[mind 'cancella la mente' &target]],},
{[ [[text]] ] = [[g &bag2 / put # &bag2 / p &bag2]],},
{[ [[text]] ] = [[mind 'invisibilita psichica']],},
{[ [[text]] ] = [[mind 'senso del pericolo']],},
{[ [[text]] ] = [[put # &bag]],},
{[ [[text]] ] = [[mind 'scudo psichico']],},
{[ [[text]] ] = [[g &bag2 / exam &bag2 / p &bag2]],},
{[ [[text]] ] = [[mind 'vuoto mentale' &target]],},
{[ [[text]] ] = [[depo 9999 ast/depo 9999 res/depo 9999 dia/depo 9999 sme/depo 9999 rub/depo 9999 zaf]],},
{[ [[text]] ] = [[mind 'lame psioniche' ]],},
{[ [[text]] ] = [[mind 'camaleonte']],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F6]],[ [[text]] ] = [[mind 'colpo superiore']],[ [[mod1]] ] = [[]],},
{[ [[text]] ] = [[mind 'manipola fiamme' potenzia]],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F2]],[ [[button]] ] = [[a1]],[ [[text]] ] = [[mind 'morsa psichica' &target]],[ [[mod1]] ] = [[]],},
}