return {{[ [[es]] ] = {2},[ [[ident]] ] = {3},[ [[lampo]] ] = {4},[ [[co]] ] = {5},[ [[disarm]] ] = {6},[ [[g]] ] = {7},[ [[cel]] ] = {8},[ [[chiaro]] ] = {9},[ [[morsa]] ] = {10},[ [[rin]] ] = {11},[ [[pi]] ] = {12},[ [[ppp]] ] = {13},[ [[golame]] ] = {14},[ [[mfc]] ] = {15},[ [[gg]] ] = {16},[ [[over]] ] = {17},[ [[tt]] ] = {18},[ [[astral]] ] = {19},[ [[x]] ] = {20},[ [[lame]] ] = {21},[ [[xxx]] ] = {22},[ [[as]] ] = {23},[ [[dro]] ] = {24},[ [[bash]] ] = {25},[ [[minibuff]] ] = {26},[ [[mfe]] ] = {27},[ [[mano]] ] = {28},[ [[ga]] ] = {29},[ [[bl]] ] = {30},[ [[sanc]] ] = {31},[ [[ramo]] ] = {32},[ [[cani]] ] = {33},[ [[scudo]] ] = {34},[ [[pugno]] ] = {35},[ [[op]] ] = {36},[ [[buff]] ] = {37},[ [[ggg]] ] = {38},[ [[goalma]] ] = {39},[ [[gogreylin]] ] = {40},[ [[rr]] ] = {41},[ [[autoattack]] ] = {42},[ [[ext]] ] = {43},[ [[flame]] ] = {44},[ [[blink]] ] = {45},[ [[pp]] ] = {46},[ [[psi]] ] = {47},[ [[sense]] ] = {48},[ [[p]] ] = {49},[ [[shield]] ] = {50},[ [[xx]] ] = {51},[ [[vuoto]] ] = {52},[ [[scry]] ] = {53},[ [[ii]] ] = {54},[ [[cham]] ] = {55},[ [[ub]] ] = {56},[ [[mfp]] ] = {57},[ [[cr]] ] = {58},},
{[ [[text]] ] = [[enter specchio]],},
{[ [[text]] ] = [[ispeziona # ident]],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F4]],[ [[text]] ] = [[mind 'lampo di energia' &target]],[ [[mod1]] ] = [[]],},
{[ [[text]] ] = [[close #/open #]],},
{[ [[text]] ] = [[gg scasso/tt scasso/usa scasso #/rr scasso/pp scasso]],},
{[ [[text]] ] = [[get # &bag]],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F12]],[ [[text]] ] = [[mind 'riparazione cellulare']],[ [[mod1]] ] = [[]],},
{[ [[text]] ] = [[mind 'chiaroveggenza']],},
{[ [[text]] ] = [[mind 'morsa brutale' &target]],},
{[ [[text]] ] = [[mind 'rinforzo psichico' &stat]],},
{[ [[text]] ] = [[mind 'pensiero imponente' &target]],},
{[ [[text]] ] = [[g &bag3/put # &bag3/p &bag3]],},
{[ [[text]] ] = [[uigo 20033]],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F7]],[ [[button]] ] = [[a3]],[ [[text]] ] = [[mind 'manipola fiamme' convoglia]],[ [[mod1]] ] = [[]],},
{[ [[text]] ] = [[g &bag2 / get # &bag2 / p &bag2]],},
{[ [[text]] ] = [[mind 'mente oltre il corpo']],},
{[ [[text]] ] = [[rem &weapon/tieni #]],},
{[ [[text]] ] = [[mind 'viaggio probabilistico']],},
{[ [[text]] ] = [[exam &bag]],},
{[ [[text]] ] = [[mind 'lame psioniche' ]],},
{[ [[text]] ] = [[g &bag3/exam &bag3/p &bag3]],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F3]],[ [[button]] ] = [[a2]],[ [[text]] ] = [[mind 'assalto psionico' &target]],[ [[mod1]] ] = [[]],},
{[ [[text]] ] = [[mind 'scarica di adrenalina']],},
{[ [[text]] ] = [[mind 'schiaffo violento' &target]],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F11]],[ [[text]] ] = [[flame/rin/shield/psi]],[ [[mod1]] ] = [[]],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F5]],[ [[text]] ] = [[mind 'manipola fiamme' espandi]],[ [[mod1]] ] = [[]],},
{[ [[text]] ] = [[mind 'mano di energia']],},
{[ [[text]] ] = [[get all]],},
{[ [[button]] ] = [[a0]],[ [[text]] ] = [[mind 'colpo psichico' &target]],},
{[ [[text]] ] = [[gg raven/tt raven/usa scettro/rr raven/pp raven]],},
{[ [[text]] ] = [[rem scudo / p scudo / g ramo / hold ramo]],},
{[ [[text]] ] = [[mind 'cannibalizzare']],},
{[ [[text]] ] = [[rem ramo / p ramo / g scudo / wear scudo]],},
{[ [[text]] ] = [[mind 'pugno serrato' &target]],},
{[ [[text]] ] = [[unlock #/open #]],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F10]],[ [[text]] ] = [[lame/minibuff]],[ [[mod1]] ] = [[]],},
{[ [[text]] ] = [[g &bag3/get # &bag3/p &bag3]],},
{[ [[text]] ] = [[uigo 3001]],},
{[ [[text]] ] = [[uigo 6246]],},
{[ [[text]] ] = [[rem #/wi &weapon]],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F1]],[ [[text]] ] = [[aa]],[ [[mod1]] ] = [[]],},
{[ [[text]] ] = [[mind 'percezione extrasensoriale']],},
{[ [[text]] ] = [[mind 'mantello di fiamme']],},
{[ [[text]] ] = [[mind 'cancella la mente' &target]],},
{[ [[text]] ] = [[g &bag2 / put # &bag2 / p &bag2]],},
{[ [[text]] ] = [[mind 'invisibilita psichica']],},
{[ [[text]] ] = [[mind 'senso del pericolo']],},
{[ [[text]] ] = [[put # &bag]],},
{[ [[text]] ] = [[mind 'scudo psichico']],},
{[ [[text]] ] = [[g &bag2 / exam &bag2 / p &bag2]],},
{[ [[text]] ] = [[mind 'vuoto mentale' &target]],},
{[ [[text]] ] = [[mind 'visione']],},
{[ [[text]] ] = [[investiga]],},
{[ [[text]] ] = [[mind 'camaleonte']],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F6]],[ [[text]] ] = [[mind 'colpo superiore']],[ [[mod1]] ] = [[]],},
{[ [[text]] ] = [[mind 'manipola fiamme' potenzia]],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F2]],[ [[button]] ] = [[a1]],[ [[text]] ] = [[mind 'morsa psichica' &target]],[ [[mod1]] ] = [[]],},
}