return {{[ [[sopra]] ] = {2},[ [[sud]] ] = {3},[ [[chiavi]] ] = {4},[ [[chiave]] ] = {5},[ [[ovest]] ] = {6},[ [[bacheca]] ] = {7},[ [[cartello]] ] = {8},[ [[est]] ] = {9},[ [[nord]] ] = {10},[ [[sotto]] ] = {11},},
{[ [[color]] ] = [[cyan]],},
{[ [[color]] ] = [[blue]],},
{[ [[color]] ] = [[cyan]],},
{[ [[color]] ] = [[cyan]],},
{[ [[color]] ] = [[violet]],},
{[ [[color]] ] = [[orange]],},
{[ [[color]] ] = [[orange]],},
{[ [[color]] ] = [[yellow]],},
{[ [[color]] ] = [[green]],},
{[ [[color]] ] = [[white]],},
}