return {{[ [[fiamme]] ] = {2},[ [[oro]] ] = {3},[ [[argento]] ] = {4},[ [[ghiaccio]] ] = {5},[ [[chiavi]] ] = {6},[ [[fuoco]] ] = {7},[ [[chiave]] ] = {8},[ [[fulmine]] ] = {9},},
{[ [[color]] ] = [[red]],},
{[ [[color]] ] = [[gold]],},
{[ [[color]] ] = [[LavenderBlush]],},
{[ [[color]] ] = [[cyan]],},
{[ [[color]] ] = [[white]],},
{[ [[color]] ] = [[red]],},
{[ [[color]] ] = [[white]],},
{[ [[color]] ] = [[gold]],},
}