return {{[ [[es]] ] = {2},[ [[lampo]] ] = {3},[ [[buff]] ] = {4},[ [[shield]] ] = {5},[ [[g]] ] = {6},[ [[cel]] ] = {7},[ [[chiaro]] ] = {8},[ [[morsa]] ] = {9},[ [[pi]] ] = {10},[ [[ppp]] ] = {11},[ [[mfc]] ] = {12},[ [[gg]] ] = {13},[ [[over]] ] = {14},[ [[dro]] ] = {15},[ [[xxx]] ] = {16},[ [[cham]] ] = {17},[ [[as]] ] = {18},[ [[bash]] ] = {19},[ [[minibuff]] ] = {20},[ [[mfe]] ] = {21},[ [[mano]] ] = {22},[ [[cr]] ] = {23},[ [[bl]] ] = {24},[ [[sanc]] ] = {25},[ [[mfp]] ] = {26},[ [[scry]] ] = {27},[ [[lame]] ] = {28},[ [[pugno]] ] = {29},[ [[op]] ] = {30},[ [[x]] ] = {31},[ [[xx]] ] = {32},[ [[vuoto]] ] = {33},[ [[p]] ] = {34},[ [[rr]] ] = {35},[ [[gogreylin]] ] = {36},[ [[autoattack]] ] = {37},[ [[flame]] ] = {38},[ [[blink]] ] = {39},[ [[ext]] ] = {40},[ [[psi]] ] = {41},[ [[sense]] ] = {42},[ [[pp]] ] = {43},[ [[goalma]] ] = {44},[ [[ggg]] ] = {45},[ [[cani]] ] = {46},[ [[ga]] ] = {47},[ [[astral]] ] = {48},[ [[tt]] ] = {49},[ [[ub]] ] = {50},[ [[golame]] ] = {51},[ [[rin]] ] = {52},},
{[ [[text]] ] = [[enter specchio]],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F4]],[ [[text]] ] = [[mind 'lampo di energia' &target]],[ [[mod1]] ] = [[]],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F10]],[ [[text]] ] = [[mano /minibuff]],[ [[mod1]] ] = [[]],},
{[ [[text]] ] = [[mind 'scudo psichico']],},
{[ [[text]] ] = [[get # &bag]],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F12]],[ [[text]] ] = [[mind 'riparazione cellulare']],[ [[mod1]] ] = [[]],},
{[ [[text]] ] = [[mind 'chiaroveggenza']],},
{[ [[text]] ] = [[mind 'morsa brutale' &target]],},
{[ [[text]] ] = [[mind 'pensiero imponente' &target]],},
{[ [[text]] ] = [[g &bag3/put # &bag3/p &bag3]],},
{[ [[button]] ] = [[a3]],[ [[text]] ] = [[mind 'manipola fiamme' convoglia]],},
{[ [[text]] ] = [[g &bag2 / get # &bag2 / p &bag2]],},
{[ [[text]] ] = [[mind 'mente oltre il corpo']],},
{[ [[text]] ] = [[mind 'scarica di adrenalina']],},
{[ [[text]] ] = [[g &bag3/exam &bag3/p &bag3]],},
{[ [[text]] ] = [[mind 'camaleonte']],},
{[ [[button]] ] = [[a2]],[ [[text]] ] = [[mind 'assalto psionico' &target]],},
{[ [[text]] ] = [[mind 'schiaffo violento' &target]],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F11]],[ [[text]] ] = [[flame / rin / shield]],[ [[mod1]] ] = [[]],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F5]],[ [[text]] ] = [[mind 'manipola fiamme' espandi]],[ [[mod1]] ] = [[]],},
{[ [[text]] ] = [[mind 'mano di energia']],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F2]],[ [[button]] ] = [[a1]],[ [[text]] ] = [[mind 'morsa psichica' &target]],[ [[mod1]] ] = [[]],},
{[ [[button]] ] = [[a0]],[ [[text]] ] = [[mind 'colpo psichico' &target]],},
{[ [[text]] ] = [[gg raven/tt raven/usa scettro/rr raven/pp raven]],},
{[ [[text]] ] = [[mind 'manipola fiamme' potenzia]],},
{[ [[text]] ] = [[mind 'visione']],},
{[ [[text]] ] = [[mind 'lame psioniche' ]],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F3]],[ [[text]] ] = [[mind 'pugno serrato' &target]],[ [[mod1]] ] = [[]],},
{[ [[text]] ] = [[unlock #/open #]],},
{[ [[text]] ] = [[exam]],},
{[ [[text]] ] = [[g &bag2 / exam &bag2 / p &bag2]],},
{[ [[text]] ] = [[mind 'vuoto mentale' &target]],},
{[ [[text]] ] = [[put # &bag]],},
{[ [[text]] ] = [[rem #/wi &weapon]],},
{[ [[text]] ] = [[uigo 6246]],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F1]],[ [[text]] ] = [[aa]],[ [[mod1]] ] = [[]],},
{[ [[text]] ] = [[mind 'mantello di fiamme']],},
{[ [[text]] ] = [[mind 'cancella la mente' &target]],},
{[ [[text]] ] = [[mind 'percezione extrasensoriale']],},
{[ [[text]] ] = [[mind 'invisibilita psichica']],},
{[ [[text]] ] = [[mind 'senso del pericolo']],},
{[ [[text]] ] = [[g &bag2 / put # &bag2 / p &bag2]],},
{[ [[text]] ] = [[uigo 3001]],},
{[ [[text]] ] = [[g &bag3/get # &bag3/p &bag3]],},
{[ [[text]] ] = [[mind 'cannibalizzare']],},
{[ [[text]] ] = [[get all]],},
{[ [[text]] ] = [[mind 'viaggio probabilistico']],},
{[ [[text]] ] = [[rem &weapon/tieni #]],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F6]],[ [[text]] ] = [[mind 'colpo superiore']],[ [[mod1]] ] = [[]],},
{[ [[text]] ] = [[uigo 20033]],},
{[ [[text]] ] = [[mind 'rinforzo psichico' &stat]],},
}