return {{[ [[c]] ] = {2},[ [[buff]] ] = {3},[ [[shield]] ] = {4},[ [[g]] ] = {5},[ [[cel]] ] = {6},[ [[chiaro]] ] = {7},[ [[morsa]] ] = {8},[ [[ppala]] ] = {9},[ [[mfc]] ] = {10},[ [[gg]] ] = {11},[ [[over]] ] = {12},[ [[dro]] ] = {13},[ [[xxx]] ] = {14},[ [[cham]] ] = {15},[ [[gpala]] ] = {16},[ [[as]] ] = {17},[ [[gfalce]] ] = {18},[ [[minibuff]] ] = {19},[ [[mfe]] ] = {20},[ [[ext]] ] = {21},[ [[bl]] ] = {22},[ [[scry]] ] = {23},[ [[rin]] ] = {24},[ [[golame]] ] = {25},[ [[pfalce]] ] = {26},[ [[pugno]] ] = {27},[ [[lame]] ] = {28},[ [[ga]] ] = {29},[ [[dd]] ] = {30},[ [[pi]] ] = {31},[ [[goalma]] ] = {32},[ [[pp]] ] = {33},[ [[cani]] ] = {34},[ [[blink]] ] = {35},[ [[flame]] ] = {36},[ [[lampo]] ] = {37},[ [[mano]] ] = {38},[ [[psi]] ] = {39},[ [[sense]] ] = {40},[ [[autoattack]] ] = {41},[ [[gogreylin]] ] = {42},[ [[p]] ] = {43},[ [[vuoto]] ] = {44},[ [[x]] ] = {45},[ [[bash]] ] = {46},[ [[xx]] ] = {47},[ [[ub]] ] = {48},[ [[mfp]] ] = {49},[ [[cr]] ] = {50},},
{[ [[text]] ] = [[cerca]],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F10]],[ [[text]] ] = [[mano /minibuff]],[ [[mod1]] ] = [[]],},
{[ [[text]] ] = [[mind 'scudo psichico']],},
{[ [[text]] ] = [[get # &bag]],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F12]],[ [[text]] ] = [[mind 'riparazione cellulare']],[ [[mod1]] ] = [[]],},
{[ [[text]] ] = [[mind 'chiaroveggenza']],},
{[ [[text]] ] = [[mind 'morsa brutale' &target]],},
{[ [[text]] ] = [[rem pala / p pala / g &weapon / wi &weapon]],},
{[ [[button]] ] = [[a3]],[ [[text]] ] = [[mind 'manipola fiamme' convoglia]],},
{[ [[text]] ] = [[g &bag2 / get # &bag2 / p &bag2]],},
{[ [[text]] ] = [[mind 'mente oltre il corpo']],},
{[ [[text]] ] = [[mind 'scarica di adrenalina']],},
{[ [[text]] ] = [[g &bag3/exam &bag3/p &bag3]],},
{[ [[text]] ] = [[mind 'camaleonte']],},
{[ [[text]] ] = [[» rem &weapon / p &weapon / g pala / wi pala]],},
{[ [[button]] ] = [[a2]],[ [[text]] ] = [[mind 'assalto psionico' &target]],},
{[ [[text]] ] = [[rem &weapon / p &weapon / g falcetto / wi falcetto]],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F11]],[ [[text]] ] = [[flame / rin / shield]],[ [[mod1]] ] = [[]],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F5]],[ [[text]] ] = [[mind 'manipola fiamme' espandi]],[ [[mod1]] ] = [[]],},
{[ [[text]] ] = [[mind 'percezione extrasensoriale']],},
{[ [[button]] ] = [[a0]],[ [[text]] ] = [[mind 'colpo psichico' &target]],},
{[ [[text]] ] = [[mind 'visione']],},
{[ [[text]] ] = [[mind 'rinforzo psichico' &stat]],},
{[ [[text]] ] = [[uigo 20033]],},
{[ [[text]] ] = [[rem falcetto / p falcetto / g &weapon / wi &weapon]],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F3]],[ [[text]] ] = [[mind 'pugno serrato' &target]],[ [[mod1]] ] = [[]],},
{[ [[text]] ] = [[mind 'lame psioniche' / uik pugno remove / uik as f3]],},
{[ [[text]] ] = [[get all]],},
{[ [[text]] ] = [[g brocca/10*drink brocca/p brocca]],},
{[ [[text]] ] = [[mind 'pensiero imponente' &target]],},
{[ [[text]] ] = [[uigo 3001]],},
{[ [[text]] ] = [[g &bag2 / put # &bag2 / p &bag2]],},
{[ [[text]] ] = [[mind 'cannibalizzare']],},
{[ [[text]] ] = [[mind 'cancella la mente' &target]],},
{[ [[text]] ] = [[mind 'mantello di fiamme']],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F4]],[ [[text]] ] = [[mind 'lampo di energia' &target]],[ [[mod1]] ] = [[]],},
{[ [[text]] ] = [[mind 'mano di energia' / uik as remove / uik pugno f3]],},
{[ [[text]] ] = [[mind 'invisibilita psichica']],},
{[ [[text]] ] = [[mind 'senso del pericolo']],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F1]],[ [[text]] ] = [[aa]],[ [[mod1]] ] = [[]],},
{[ [[text]] ] = [[uigo 6246]],},
{[ [[text]] ] = [[put # &bag]],},
{[ [[text]] ] = [[mind 'vuoto mentale' &target]],},
{[ [[text]] ] = [[exam]],},
{[ [[text]] ] = [[mind 'schiaffo violento' &target]],},
{[ [[text]] ] = [[g &bag2 / exam &bag2 / p &bag2]],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F6]],[ [[text]] ] = [[mind 'colpo superiore']],[ [[mod1]] ] = [[]],},
{[ [[text]] ] = [[mind 'manipola fiamme' potenzia]],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F2]],[ [[button]] ] = [[a1]],[ [[text]] ] = [[mind 'morsa psichica' &target]],[ [[mod1]] ] = [[]],},
}