return {{[ [[c]] ] = {2},[ [[buff]] ] = {3},[ [[shield]] ] = {4},[ [[g]] ] = {5},[ [[cel]] ] = {6},[ [[chiaro]] ] = {7},[ [[morsa]] ] = {8},[ [[p]] ] = {9},[ [[mfc]] ] = {10},[ [[gg]] ] = {11},[ [[over]] ] = {12},[ [[dro]] ] = {13},[ [[lame]] ] = {14},[ [[cham]] ] = {15},[ [[falce]] ] = {16},[ [[as]] ] = {17},[ [[bash]] ] = {18},[ [[minibuff]] ] = {19},[ [[mfe]] ] = {20},[ [[ext]] ] = {21},[ [[bl]] ] = {22},[ [[scry]] ] = {23},[ [[rfalce]] ] = {24},[ [[gogreylin]] ] = {25},[ [[rin]] ] = {26},[ [[golame]] ] = {27},[ [[rpala]] ] = {28},[ [[ga]] ] = {29},[ [[pi]] ] = {30},[ [[pp]] ] = {31},[ [[pugno]] ] = {32},[ [[cani]] ] = {33},[ [[flame]] ] = {34},[ [[goalma]] ] = {35},[ [[blink]] ] = {36},[ [[psi]] ] = {37},[ [[sense]] ] = {38},[ [[lampo]] ] = {39},[ [[mano]] ] = {40},[ [[autoattack]] ] = {41},[ [[vuoto]] ] = {42},[ [[pala]] ] = {43},[ [[x]] ] = {44},[ [[xx]] ] = {45},[ [[ub]] ] = {46},[ [[mfp]] ] = {47},[ [[cr]] ] = {48},},
{[ [[text]] ] = [[cerca]],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F10]],[ [[text]] ] = [[flame / mano / rin / minibuff]],[ [[mod1]] ] = [[]],},
{[ [[text]] ] = [[mind 'scudo psichico']],},
{[ [[text]] ] = [[get # &bag]],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F12]],[ [[text]] ] = [[mind 'riparazione cellulare']],[ [[mod1]] ] = [[]],},
{[ [[text]] ] = [[mind 'chiaroveggenza']],},
{[ [[text]] ] = [[mind 'morsa brutale' &target]],},
{[ [[text]] ] = [[put # &bag]],},
{[ [[button]] ] = [[a3]],[ [[text]] ] = [[mind 'manipola fiamme' convoglia]],},
{[ [[text]] ] = [[g &bag2 / get # &bag2 / p &bag2]],},
{[ [[text]] ] = [[mind 'mente oltre il corpo']],},
{[ [[text]] ] = [[mind 'scarica di adrenalina']],},
{[ [[text]] ] = [[mind 'lame psioniche' / uik pugno remove / uik as f3]],},
{[ [[text]] ] = [[mind 'camaleonte']],},
{[ [[text]] ] = [[rem &weapon / p &weapon / g falcetto / wi falcetto]],},
{[ [[button]] ] = [[a2]],[ [[text]] ] = [[mind 'assalto psionico' &target]],},
{[ [[text]] ] = [[mind 'schiaffo violento' &target]],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F11]],[ [[text]] ] = [[shield/dro/psi]],[ [[mod1]] ] = [[]],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F5]],[ [[text]] ] = [[mind 'manipola fiamme' espandi]],[ [[mod1]] ] = [[]],},
{[ [[text]] ] = [[mind 'percezione extrasensoriale']],},
{[ [[button]] ] = [[a0]],[ [[text]] ] = [[mind 'colpo psichico' &target]],},
{[ [[text]] ] = [[mind 'visione']],},
{[ [[text]] ] = [[rem falcetto / p falcetto / g &weapon / wi &weapon]],},
{[ [[text]] ] = [[uigo 6246]],},
{[ [[text]] ] = [[mind 'rinforzo psichico' &stat]],},
{[ [[text]] ] = [[uigo 20033]],},
{[ [[text]] ] = [[rem pala / p pala / g &weapon / wi &weapon]],},
{[ [[text]] ] = [[get all]],},
{[ [[text]] ] = [[mind 'pensiero imponente' &target]],},
{[ [[text]] ] = [[g &bag2 / put # &bag2 / p &bag2]],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F3]],[ [[text]] ] = [[mind 'pugno serrato' &target]],[ [[mod1]] ] = [[]],},
{[ [[text]] ] = [[mind 'cannibalizzare']],},
{[ [[text]] ] = [[mind 'mantello di fiamme']],},
{[ [[text]] ] = [[uigo 3001]],},
{[ [[text]] ] = [[mind 'cancella la mente' &target]],},
{[ [[text]] ] = [[mind 'invisibilita psichica']],},
{[ [[text]] ] = [[mind 'senso del pericolo']],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F4]],[ [[text]] ] = [[mind 'lampo di energia' &target]],[ [[mod1]] ] = [[]],},
{[ [[text]] ] = [[mind 'mano di energia' / uik as remove / uik pugno f3]],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F1]],[ [[text]] ] = [[aa]],[ [[mod1]] ] = [[]],},
{[ [[text]] ] = [[mind 'vuoto mentale' &target]],},
{[ [[text]] ] = [[rem &weapon / p &weapon / g pala / wi pala]],},
{[ [[text]] ] = [[exam]],},
{[ [[text]] ] = [[g &bag2 / exam &bag2 / p &bag2]],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F6]],[ [[text]] ] = [[mind 'colpo superiore']],[ [[mod1]] ] = [[]],},
{[ [[text]] ] = [[mind 'manipola fiamme' potenzia]],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F2]],[ [[button]] ] = [[a1]],[ [[text]] ] = [[mind 'frantumazione psichica' &target]],[ [[mod1]] ] = [[]],},
}