return {{[ [[lampo]] ] = {2},[ [[buff]] ] = {3},[ [[shield]] ] = {4},[ [[g]] ] = {5},[ [[cel]] ] = {6},[ [[cc]] ] = {7},[ [[ga]] ] = {8},[ [[morsa]] ] = {9},[ [[p]] ] = {10},[ [[mfc]] ] = {11},[ [[over]] ] = {12},[ [[dro]] ] = {13},[ [[lame]] ] = {14},[ [[cham]] ] = {15},[ [[as]] ] = {16},[ [[bash]] ] = {17},[ [[minibuff]] ] = {18},[ [[mfe]] ] = {19},[ [[mano]] ] = {20},[ [[bl]] ] = {21},[ [[scry]] ] = {22},[ [[autoattack]] ] = {23},[ [[rin]] ] = {24},[ [[golame]] ] = {25},[ [[chiaro]] ] = {26},[ [[flame]] ] = {27},[ [[pi]] ] = {28},[ [[gogreylin]] ] = {29},[ [[psi]] ] = {30},[ [[sense]] ] = {31},[ [[goalma]] ] = {32},[ [[cani]] ] = {33},[ [[blink]] ] = {34},[ [[vuoto]] ] = {35},[ [[ext]] ] = {36},[ [[pugno]] ] = {37},[ [[x]] ] = {38},[ [[ub]] ] = {39},[ [[mfp]] ] = {40},[ [[cr]] ] = {41},},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F4]],[ [[text]] ] = [[mind 'lampo di energia' &target]],[ [[mod1]] ] = [[]],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F10]],[ [[text]] ] = [[flame / mano / rin / minibuff]],[ [[mod1]] ] = [[]],},
{[ [[text]] ] = [[mind 'scudo psichico']],},
{[ [[text]] ] = [[rem &bag / get # &bag / wear &bag]],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F12]],[ [[text]] ] = [[mind 'riparazione cellulare']],[ [[mod1]] ] = [[]],},
{[ [[text]] ] = [[cerca]],},
{[ [[text]] ] = [[get all]],},
{[ [[text]] ] = [[mind 'morsa brutale' &target]],},
{[ [[text]] ] = [[rem &bag/put # &bag/wear &bag]],},
{[ [[button]] ] = [[a3]],[ [[text]] ] = [[mind 'manipola fiamme' convoglia]],},
{[ [[text]] ] = [[mind 'mente oltre il corpo']],},
{[ [[text]] ] = [[mind 'scarica di adrenalina']],},
{[ [[text]] ] = [[mind 'lame psioniche' / uik pugno remove / uik as f3]],},
{[ [[text]] ] = [[mind 'camaleonte']],},
{[ [[button]] ] = [[a2]],[ [[text]] ] = [[mind 'assalto psionico' &target]],},
{[ [[text]] ] = [[mind 'schiaffo violento' &target]],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F11]],[ [[text]] ] = [[shield/dro/psi]],[ [[mod1]] ] = [[]],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F5]],[ [[text]] ] = [[mind 'manipola fiamme' espandi]],[ [[mod1]] ] = [[]],},
{[ [[text]] ] = [[mind 'mano di energia' / uik as remove / uik pugno f3]],},
{[ [[button]] ] = [[a0]],[ [[text]] ] = [[mind 'colpo psichico' &target]],},
{[ [[text]] ] = [[mind 'visione']],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F1]],[ [[text]] ] = [[aa]],[ [[mod1]] ] = [[]],},
{[ [[text]] ] = [[mind 'rinforzo psichico' &stat]],},
{[ [[text]] ] = [[uigo 20033]],},
{[ [[text]] ] = [[mind 'chiaroveggenza']],},
{[ [[text]] ] = [[mind 'mantello di fiamme']],},
{[ [[text]] ] = [[mind 'pensiero imponente' &target]],},
{[ [[text]] ] = [[uigo 6246]],},
{[ [[text]] ] = [[mind 'invisibilita psichica']],},
{[ [[text]] ] = [[mind 'senso del pericolo']],},
{[ [[text]] ] = [[uigo 3001]],},
{[ [[text]] ] = [[mind 'cannibalizzare']],},
{[ [[text]] ] = [[mind 'cancella la mente' &target]],},
{[ [[text]] ] = [[mind 'vuoto mentale' &target]],},
{[ [[text]] ] = [[mind 'percezione extrasensoriale']],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F3]],[ [[text]] ] = [[mind 'pugno serrato' &target]],[ [[mod1]] ] = [[]],},
{[ [[text]] ] = [[exam]],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F6]],[ [[text]] ] = [[mind 'colpo superiore']],[ [[mod1]] ] = [[]],},
{[ [[text]] ] = [[mind 'manipola fiamme' potenzia]],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F2]],[ [[button]] ] = [[a1]],[ [[text]] ] = [[mind 'frantumazione psichica' &target]],[ [[mod1]] ] = [[]],},
}