return {{[ [[es]] ] = {2},[ [[ident]] ] = {3},[ [[ggg]] ] = {4},[ [[buff]] ] = {5},[ [[fu]] ] = {6},[ [[di]] ] = {7},[ [[g]] ] = {8},[ [[pelle]] ] = {9},[ [[pavese]] ] = {10},[ [[ga]] ] = {11},[ [[www]] ] = {12},[ [[da]] ] = {13},[ [[pi]] ] = {14},[ [[ppp]] ] = {15},[ [[gg]] ] = {16},[ [[po]] ] = {17},[ [[tt]] ] = {18},[ [[astral]] ] = {19},[ [[x]] ] = {20},[ [[im]] ] = {21},[ [[tele]] ] = {22},[ [[bash]] ] = {23},[ [[minibuff]] ] = {24},[ [[ep]] ] = {25},[ [[sanc]] ] = {26},[ [[op]] ] = {27},[ [[or]] ] = {28},[ [[xx]] ] = {29},[ [[sfera]] ] = {30},[ [[rr]] ] = {31},[ [[armor]] ] = {32},[ [[fly]] ] = {33},[ [[flame]] ] = {34},[ [[dw]] ] = {35},[ [[pp]] ] = {36},[ [[vel]] ] = {37},[ [[str]] ] = {38},[ [[shield]] ] = {39},[ [[myopen]] ] = {40},[ [[cell]] ] = {41},[ [[invi]] ] = {42},[ [[xxx]] ] = {43},[ [[ice]] ] = {44},[ [[fa]] ] = {45},[ [[p]] ] = {46},[ [[ta]] ] = {47},[ [[attack]] ] = {48},},
{[ [[text]] ] = [[enter specchio]],},
{[ [[text]] ] = [[cast 'identificazione' #]],},
{[ [[text]] ] = [[g @bag2/get # @bag2/p @bag2]],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F10]],[ [[text]] ] = [[str kc / shield kc / armor kc / pelle kc / po kc / minibuff]],[ [[mod1]] ] = [[]],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F1]],[ [[text]] ] = [[cast 'fulmine' @target]],[ [[mod1]] ] = [[]],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F3]],[ [[text]] ] = [[cast 'disintegrazione' @target]],[ [[mod1]] ] = [[]],},
{[ [[text]] ] = [[get # @bag]],},
{[ [[text]] ] = [[cast 'pelle di pietra' @target]],},
{[ [[text]] ] = [[rem sfera/pp sfera/gg pavese/wear pavese]],},
{[ [[text]] ] = [[get all]],},
{[ [[text]] ] = [[where spirito/where massa/where forma/where corpo/where mostro]],},
{[ [[text]] ] = [[cast 'dardo' @target]],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F2]],[ [[text]] ] = [[cast 'pioggia di meteore' @target]],[ [[mod1]] ] = [[]],},
{[ [[text]] ] = [[g @bag2/put # @bag2/p @bag2]],},
{[ [[text]] ] = [[g @bag1/get # @bag1/p @bag1]],},
{[ [[text]] ] = [[cast 'potere arcano' @target]],},
{[ [[text]] ] = [[rem @weapon/tieni #]],},
{[ [[text]] ] = [[cast 'teletrasporto sicuro']],},
{[ [[text]] ] = [[examine]],},
{[ [[text]] ] = [[info mob]],},
{[ [[text]] ] = [[cast 'teletrasporto' @target]],},
{[ [[text]] ] = [[cast 'folata di vento']],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F11]],[ [[text]] ] = [[ice kc / vel /first]],[ [[mod1]] ] = [[]],},
{[ [[text]] ] = [[enter portal]],},
{[ [[text]] ] = [[gg raven/tt raven/usa scettro/rr raven/pp raven]],},
{[ [[text]] ] = [[cast 'knock' #/pick # / unlock # / open #]],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F7]],[ [[text]] ] = [[cast 'orrido avvizzimento']],[ [[mod1]] ] = [[]],},
{[ [[text]] ] = [[g @bag1/x @bag1/p @bag1]],},
{[ [[text]] ] = [[rem pavese/pp pavese/gg rutilante/wear rutilante]],},
{[ [[text]] ] = [[rem #/wi @weapon]],},
{[ [[text]] ] = [[cast 'armatura' @target]],},
{[ [[text]] ] = [[cast 'volo' @target]],},
{[ [[text]] ] = [[cast 'scudo di fuoco']],},
{[ [[text]] ] = [[cast 'portale' # / ent por]],},
{[ [[text]] ] = [[g @bag1/put # @bag1/p @bag1]],},
{[ [[text]] ] = [[enve lee]],},
{[ [[text]] ] = [[cast 'possanza' @target]],},
{[ [[text]] ] = [[cast 'scudo' kc]],},
{[ [[text]] ] = [[open #/push #/pull #/turn #/lift #/twist #]],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F4]],[ [[text]] ] = [[cast 'fonte di potere']],[ [[mod1]] ] = [[]],},
{[ [[text]] ] = [[cast 'invisibilita' @target]],},
{[ [[text]] ] = [[g @bag2/x @bag2/p @bag2]],},
{[ [[text]] ] = [[cast 'scudo di ghiaccio']],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F6]],[ [[text]] ] = [[cast 'fulmini a catena']],[ [[mod1]] ] = [[]],},
{[ [[text]] ] = [[put # @bag]],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F5]],[ [[text]] ] = [[cast 'tempesta di ghia']],[ [[mod1]] ] = [[]],},
{[ [[text]] ] = [[fu]],},
}