return {{[ [[enablePugno]] ] = true,[ [[freeCast]] ] = false,[ [[autoAttackArea]] ] = true,[ [[autoAttack]] ] = true,[ [[page]] ] = [[a]],[ [[widgets]] ] = {2},},
{[ [[endowment]] ] = {3},[ [[keybind]] ] = {4},[ [[group]] ] = {5},[ [[aliasButton]] ] = {6},[ [[chat]] ] = {7},[ [[player]] ] = {8},[ [[help]] ] = {9},[ [[affects]] ] = {10},[ [[targets]] ] = {11},[ [[room]] ] = {12},[ [[opponent]] ] = {13},},
{[ [[type]] ] = [[equip]],[ [[transparent]] ] = false,},
{[ [[fontSize]] ] = 6,},
{[ [[transparent]] ] = false,},
{[ [[transparent]] ] = false,},
{[ [[fontSize]] ] = 9,[ [[split]] ] = [[vertical]],[ [[collapsePublic]] ] = true,[ [[type]] ] = [[private]],[ [[collapsePrivate]] ] = true,},
{[ [[transparent]] ] = false,},
{[ [[fontSize]] ] = 9,},
{[ [[transparent]] ] = false,},
{[ [[transparent]] ] = true,},
{[ [[fontSize]] ] = 9,[ [[transparent]] ] = false,},
{[ [[transparent]] ] = false,},
}