return {{[ [[page]] ] = [[a]],[ [[widgets]] ] = {2},},
{[ [[endowment]] ] = {3},[ [[keybind]] ] = {4},[ [[group]] ] = {5},[ [[aliasButton]] ] = {6},[ [[chat]] ] = {7},[ [[player]] ] = {8},[ [[help]] ] = {9},[ [[affects]] ] = {10},[ [[targets]] ] = {11},[ [[room]] ] = {12},[ [[opponent]] ] = {13},},
{[ [[type]] ] = [[equip]],[ [[transparent]] ] = false,},
{[ [[fontSize]] ] = 6,},
{[ [[transparent]] ] = false,},
{[ [[transparent]] ] = false,},
{[ [[type]] ] = [[all]],[ [[fontSize]] ] = 10,[ [[split]] ] = [[horizontal]],},
{[ [[transparent]] ] = false,},
{[ [[fontSize]] ] = 10,},
{[ [[transparent]] ] = false,},
{[ [[transparent]] ] = false,},
{[ [[fontSize]] ] = 10,[ [[transparent]] ] = false,},
{[ [[transparent]] ] = false,},
}