return {{[ [[str]] ] = {2},[ [[ggg]] ] = {3},[ [[buff]] ] = {4},[ [[shield]] ] = {5},[ [[di]] ] = {6},[ [[g]] ] = {7},[ [[pavese]] ] = {8},[ [[aura]] ] = {9},[ [[chiaro]] ] = {10},[ [[cell]] ] = {11},[ [[xx]] ] = {12},[ [[bu]] ] = {13},[ [[p]] ] = {14},[ [[ppp]] ] = {15},[ [[bash]] ] = {16},[ [[great]] ] = {17},[ [[gg]] ] = {18},[ [[over]] ] = {19},[ [[tt]] ] = {20},[ [[xxx]] ] = {21},[ [[cham]] ] = {22},[ [[dis]] ] = {23},[ [[myopen]] ] = {24},[ [[tele]] ] = {25},[ [[dro]] ] = {26},[ [[wipe]] ] = {27},[ [[minibuff]] ] = {28},[ [[bl]] ] = {29},[ [[mano]] ] = {30},[ [[scry]] ] = {31},[ [[ep]] ] = {32},[ [[sfera]] ] = {33},[ [[sanc]] ] = {34},[ [[ga]] ] = {35},[ [[im]] ] = {36},[ [[autoattack]] ] = {37},[ [[op]] ] = {38},[ [[astral]] ] = {39},[ [[sense]] ] = {40},[ [[psi]] ] = {41},[ [[fly]] ] = {42},[ [[rr]] ] = {43},[ [[pp]] ] = {44},[ [[extra]] ] = {45},[ [[flame]] ] = {46},[ [[portal]] ] = {47},[ [[es]] ] = {48},[ [[vel]] ] = {49},[ [[blank]] ] = {50},[ [[pugno]] ] = {51},[ [[dw]] ] = {52},[ [[ipno]] ] = {53},[ [[cani]] ] = {54},[ [[sum]] ] = {55},[ [[www]] ] = {56},[ [[attack]] ] = {57},[ [[ub]] ] = {58},[ [[x]] ] = {59},[ [[cr]] ] = {60},},
{[ [[text]] ] = [[mind 'forza psichica']],},
{[ [[text]] ] = [[g @bag2/get # @bag2/p @bag2]],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F10]],[ [[text]] ] = [[minibuff/str/shield]],[ [[mod1]] ] = [[]],},
{[ [[text]] ] = [[mind 'scudo psichico']],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F3]],[ [[text]] ] = [[mind 'disintegrazione psichica' @target]],[ [[mod1]] ] = [[]],},
{[ [[text]] ] = [[get # @bag]],},
{[ [[text]] ] = [[rem sfera/pp sfera/gg pavese/wear pavese]],},
{[ [[text]] ] = [[mind 'aura veggente']],},
{[ [[text]] ] = [[mind 'chiaroveggenza']],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F12]],[ [[text]] ] = [[mind 'riparazione cellulare']],[ [[mod1]] ] = [[]],},
{[ [[text]] ] = [[g @bag1/x @bag1/p @bag1]],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F5]],[ [[text]] ] = [[mind 'mente bruc']],[ [[mod1]] ] = [[]],},
{[ [[text]] ] = [[put # @bag]],},
{[ [[text]] ] = [[g @bag2/put # @bag2/p @bag2]],},
{[ [[text]] ] = [[mind 'telecinesi' @target]],},
{[ [[text]] ] = [[mind 'grande vista']],},
{[ [[text]] ] = [[g @bag1/get # @bag1/p @bag1]],},
{[ [[text]] ] = [[mind 'mente oltre il corpo']],},
{[ [[text]] ] = [[rem @weapon/tieni #]],},
{[ [[text]] ] = [[g @bag2/x @bag2/p @bag2]],},
{[ [[text]] ] = [[mind 'camaleonte']],},
{[ [[text]] ] = [[mind 'lampo di energia' @target]],},
{[ [[text]] ] = [[open #/push #/pull #/turn #/lift #/twist #]],},
{[ [[text]] ] = [[mind 'teletrasporto psichico']],},
{[ [[text]] ] = [[mind 'scarica di adrenalina']],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F7]],[ [[text]] ] = [[mind 'cancella la mente' @target]],[ [[mod1]] ] = [[]],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F11]],[ [[text]] ] = [[flame/dro Kyrus/vel/first]],[ [[mod1]] ] = [[]],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F1]],[ [[text]] ] = [[mind 'colpo psichico' @target]],[ [[mod1]] ] = [[]],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F8]],[ [[text]] ] = [[mind 'mano stringente' @target]],[ [[mod1]] ] = [[]],},
{[ [[text]] ] = [[mind 'visione']],},
{[ [[text]] ] = [[enter portal]],},
{[ [[text]] ] = [[rem pavese/pp pavese/gg rutilante/wear rutilante]],},
{[ [[text]] ] = [[gg raven/tt raven/usa scettro/rr raven/pp raven]],},
{[ [[text]] ] = [[get all]],},
{[ [[text]] ] = [[info mob]],},
{[ [[text]] ] = [[aa]],},
{[ [[text]] ] = [[unlock #/open #]],},
{[ [[text]] ] = [[mind 'viaggio probabilistico']],},
{[ [[text]] ] = [[mind 'senso del pericolo']],},
{[ [[text]] ] = [[mind 'invisibilita psichica']],},
{[ [[text]] ] = [[mind 'levitazione']],},
{[ [[text]] ] = [[rem #/wi @weapon]],},
{[ [[text]] ] = [[g @bag1/put # @bag1/p @bag1]],},
{[ [[text]] ] = [[mind 'percezione extrasensoriale']],},
{[ [[text]] ] = [[mind 'mantello di fiamme']],},
{[ [[text]] ] = [[mind 'portale psichico']],},
{[ [[text]] ] = [[enter specchio]],},
{[ [[text]] ] = [[enve lee]],},
{[ [[text]] ] = [[mind 'vuoto mentale']],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F9]],[ [[text]] ] = [[mind 'pugno serrato' @target]],[ [[mod1]] ] = [[]],},
{[ [[text]] ] = [[mind 'trasferimento']],},
{[ [[text]] ] = [[mind 'ipnosi']],},
{[ [[text]] ] = [[mind 'cannibalizzare']],},
{[ [[text]] ] = [[mind 'evocazione psichica']],},
{[ [[text]] ] = [[where spirito/where massa/where forma/where corpo/where mostro]],},
{[ [[text]] ] = [[bl]],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F6]],[ [[text]] ] = [[mind 'colpo superiore']],[ [[mod1]] ] = [[]],},
{[ [[text]] ] = [[examine]],},
{[ [[mod2]] ] = [[]],[ [[key]] ] = [[F2]],[ [[text]] ] = [[mind 'frantumazione psichica' @target]],[ [[mod1]] ] = [[]],},
}